const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const c={Session:{getScriptTimeZone:()=> 'Asia/Kuala_Lumpur'},Utilities:{formatDate:()=> '2026-09-10',newBlob:()=>({getAs:()=>({getBytes:()=>[]})}),base64Encode:()=>''},MimeType:{HTML:'html',PDF:'pdf'}};
vm.createContext(c);vm.runInContext(fs.readFileSync('gas/Code.js','utf8'),c);
const order=(id,name='SAM',date='2026-09-09')=>({ORDER_ID:id,SALESMAN:name,BRANCH:'BRANCH',DATE:date,MONTH:9,INVOICE_TO:'SA',SET_TYPE:'BAG',QTY:10,UNIT_PRICE:55,TOTAL_INCOME:550});
let orders=[order('A'),order('B'),order('C','OTHER'),order('D','SAM','2026-08-09')], issued=[], rendered;
const head=['INV_NO','YM','CUST_KEY','SALESMAN','BILL_MODE','BILL_NAME','ORDERS','AMOUNT','ISSUED_AT','ISSUED_BY','STATUS','VOID_AT','VOID_BY','VOID_REASON','ORDER_IDS','SNAPSHOT_JSON'];
const sm={rows:[{SALESMAN:'SAM',BRANCH:'BRANCH','发票方式':'逐笔'},{SALESMAN:'OTHER',BRANCH:'BRANCH'}]};
c.ensureCols_=name=>name==='ORDERS'?{rows:orders}:name==='SALESMAN'?sm:{rows:[]};
c.readTable_=()=>({rows:orders});c.fmtDate_=x=>x;c.shortDate_=x=>x;c.invBrandList_=()=>[];c.invBrandOf_=()=>'';c.invNameFor_=()=> 'BAG';c.unitOf_=()=> 'pcs';
c.withLock_=fn=>fn();c.invoiceHtml_=(iv,no)=>{rendered=JSON.parse(JSON.stringify({iv,no}));return 'html';};
c.invSheet_=()=>({head,rows:issued,sheet:{appendRow(values){issued.push({...Object.fromEntries(head.map((h,i)=>[h,values[i]])),__row:issued.length+3});},getRange(row,col){return {setValues(values){Object.assign(issued.find(r=>r.__row===row),Object.fromEntries(head.map((h,i)=>[h,values[0][i]])));},setValue(value){issued.find(r=>r.__row===row)[head[col-1]]=value;}};}}});
c.logChange_=()=>{};
let n=0;function check(v,msg){assert.ok(v,msg);n++;}
let list=c.listInvoiceMonth({ym:'2609'});check(list.list.filter(x=>x.salesman==='SAM').length===2,'per order default preserved');
let r=c.makeInvoicePdf({ym:'2609',orderIds:['A','C']});check(!r.ok&&issued.length===0,'different customers rejected');
r=c.makeInvoicePdf({ym:'2609',orderIds:['A','B'],expectedTotal:1000});check(!r.ok&&issued.length===0,'changed total requires fresh confirmation');
orders.push({...order('COMPANY'),INVOICE_TO:'COMPANY'});
r=c.makeInvoicePdf({ym:'2609',orderIds:['A','COMPANY']});check(!r.ok,'personal and company billing cannot mix');
orders.pop();
r=c.makeInvoicePdf({ym:'2609',orderIds:['A','D']});check(!r.ok,'cross month rejected');
r=c.makeInvoicePdf({ym:'2609',orderIds:['A','A']});check(!r.ok,'duplicates rejected');
r=c.makeInvoicePdf({ym:'2609',orderIds:['MISSING']});check(!r.ok,'missing orders rejected');
r=c.makeInvoicePdf({ym:'2609',orderIds:['A','B']});check(r.ok&&r.total===1100&&r.lines===2,'selected orders combine into one PDF');
const no=r.invNo, snapshot=JSON.stringify(rendered.iv);check(issued.length===1&&JSON.parse(issued[0].ORDER_IDS).length===2,'mapping persisted with snapshot');
r=c.makeInvoicePdf({ym:'2609',orderIds:['B','A']});check(!r.ok&&issued.length===1,'double click cannot issue twice');
list=c.listInvoiceMonth({ym:'2609'});check(list.candidates.filter(x=>x.invNo===no).length===2,'selected orders show original invoice');
check(list.list.filter(x=>x.salesman==='SAM').length===1,'issued orders removed from pending groups');
orders[0].TOTAL_INCOME=1;orders.push(order('E'));
r=c.makeInvoicePdf({invNo:no});check(r.ok&&JSON.stringify(rendered.iv)===snapshot,'reprint stays fixed after edits and later orders');
r=c.voidInvoice({invNo:no,reason:'合并重开'});check(r.ok,'void invoice keeps number and releases mapping');
orders[0].TOTAL_INCOME=550;
r=c.makeInvoicePdf({ym:'2609',orderIds:['A','B','E']});check(r.ok&&r.invNo!==no&&r.total===1650,'voided orders can be regrouped with a new number');
check(!c.makeInvoicePdf({invNo:no}).ok,'voided invoice cannot be reprinted as active');
issued=[];orders=[order('A'),order('B')];
issued.push({INV_NO:'INV-2609-005',YM:'2609',CUST_KEY:'SAM|SA#B',SALESMAN:'SAM',BILL_MODE:'SA',BILL_NAME:'SAM',ORDERS:1,AMOUNT:550,__row:3});
check(!c.makeInvoicePdf({ym:'2609',orderIds:['A','B']}).ok,'legacy per order invoice blocks selected merge');
list=c.listInvoiceMonth({ym:'2609'});check(list.candidates.find(x=>x.id==='B').invNo==='INV-2609-005','legacy invoice stays visible');
c.makeInvoicePdf({invNo:'INV-2609-005'});check(!!issued[0].SNAPSHOT_JSON,'legacy reprint gains snapshot after matching total and count');
c.voidInvoice({invNo:'INV-2609-005',reason:'合并重开'});
r=c.makeInvoicePdf({ym:'2609',orderIds:['A','B']});check(r.ok&&r.invNo==='INV-2609-006','customer screenshot scenario works without deleting orders');
issued=[{INV_NO:'INV-2609-009',YM:'2609',CUST_KEY:'SAM|SA',SALESMAN:'SAM',ORDERS:1,AMOUNT:550,__row:3}];
check(!c.makeInvoicePdf({ym:'2609',orderIds:['A']}).ok,'legacy monthly invoice reserves customer month');
check(!c.makeInvoicePdf({invNo:'INV-2609-009'}).ok,'changed legacy monthly invoice cannot silently reprint changed totals');
issued=[];c.Utilities.newBlob=()=>{throw Error('PDF service failed');};
r=c.makeInvoicePdf({ym:'2609',orderIds:['A']});check(!r.ok&&issued.length===1&&!!issued[0].SNAPSHOT_JSON,'PDF failure preserves number and snapshot for retry');
check(!c.makeInvoicePdf({ym:'2609',orderIds:['A']}).ok,'PDF failure cannot issue duplicate');
console.log(n+' invoice merge backend assertions passed');
