const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');
const html = fs.readFileSync('gas/Index.html', 'utf8').replace(/<\?=.*?\?>/g, 'TEST');
const row = (id, salesman='TEST', paid=false) => ({id,salesman,branch:'TEST BRANCH',date:'2026-09-01',setType:'BAG',qty:1,total:10,mine:2,fee:1,paid,method:paid?'OP':''});
const report = n => ({total:{orders:n,sets:n,income:n*10,mine:n*2,fee:n,unpaid:0,unpaidN:0},months:[],branches:[],sets:[],regions:[],driverPayable:n,allowance:0,nMonths:1});
let count=0;
function check(value, message){assert.ok(value,message);count++}
const flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve()};
async function main(){
  const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'https://test.local'});
  const w=dom.window,d=w.document,requests=[];
  w.confirm=()=>true;
  // The real bridge runs; only google.script.run's transport is controlled.
  const rpc={};
  rpc.withSuccessHandler=success=>({withFailureHandler:failure=>new Proxy({}, {get:(_,fn)=>(...args)=>requests.push({fn,args,resolve:success,reject:failure})})});
  w.google={script:{run:rpc}};w.HAS_GS=true;
  w.S.user={name:'TEST',role:'admin'};w.S.boot={driver:{phone:'',name:'TEST'},setUnits:{}};
  w.S.view='list';d.getElementById('app').innerHTML='<div id="v-list"></div><div id="v-dash"></div><div id="v-set"></div>';
  const take=fn=>{const i=requests.findIndex(r=>r.fn===fn);assert.notEqual(i,-1,'expected '+fn);return requests.splice(i,1)[0]};
  let p=w.loadList();check(!!d.querySelector('.spin'),'first load shows progress');
  take('getOrders').resolve([row('A')]);await p;
  check(d.getElementById('olist').textContent.includes('TEST'),'initial orders render');
  const before=requests.length;await w.loadList();check(requests.length===before,'fresh revisit has no RPC');
  check(!d.querySelector('.spin'),'fresh revisit has no blocking spinner');
  let input=d.querySelector('#v-list input');input.value='TEST';input.focus();input.setSelectionRange(2,2);w.filterList(input.value);
  Object.values(w.VIEW_READ.cache).forEach(e=>e.at-=16000);
  p=w.loadList();let p2=w.loadList();check(requests.length===1,'overlapping reads deduplicated');
  check(d.getElementById('olist').textContent.includes('TEST'),'stale data remains while updating');
  take('getOrders').resolve([row('B')]);await Promise.all([p,p2]);
  check(d.querySelector('#v-list input')===input&&d.activeElement===input&&input.selectionStart===2,'background refresh preserves input and caret');
  check(w.S.orderQuery==='TEST','search preserved');
  p=w.loadList(true);take('getOrders').reject(new Error('offline'));await p;
  check(d.getElementById('olist').textContent.includes('TEST'),'offline retains last data');
  check(d.querySelector('.read-status').textContent.includes('更新失败'),'offline clearly labels old data');
  p=w.loadList(true);take('getOrders').resolve([row('C')]);await p;check(w.S.orders[0].id==='C','manual retry refreshes');
  w.S.month=1;p=w.loadList();const jan=take('getOrders');w.S.month=2;p2=w.loadList();const feb=take('getOrders');
  feb.resolve([row('FEB')]);await p2;jan.resolve([row('JAN')]);await p;
  check(w.S.orders[0].id==='FEB','out-of-order month responses cannot overwrite selection');
  p=w.loadList(true);const old=take('getOrders');
  const saving=w.call('markPaid',[{id:'FEB',method:'OP',date:'2026-09-01'}]);
  check(Object.keys(w.VIEW_READ.cache).length===0,'write starts invalidate snapshots');
  take('markPaid').resolve({ok:true});await saving;
  old.resolve([row('FEB')]);await flush();
  take('getOrders').resolve([row('FEB','TEST',true)]);await p;
  check(w.S.orders[0].paid===true,'read racing a save refetches instead of restoring unpaid state');
  w.S.view='dash';p=w.loadDash();take('getDashboard').resolve(report(2));await p;
  check(w.S.dash.total.orders===2,'dashboard renders');await w.loadDash();check(requests.length===0,'dashboard revisit has no RPC');
  const update=w.call('updateOrder',[{id:'FEB'}]);take('updateOrder').resolve({ok:true});await update;
  p=w.loadDash();check(!!d.querySelector('#v-dash .spin'),'changed data is not shown as current');take('getDashboard').resolve(report(3));await p;
  check(w.S.dash.total.orders===3,'dashboard reloads after order mutation');
  w.S.view='list';w.S.month=0;p=w.loadList();const hidden=take('getOrders');w.S.view='dash';hidden.resolve([row('HIDDEN')]);await p;
  check(w.S.orders[0].id==='FEB','hidden response does not change visible shared state');
  w.S.view='list';await w.loadList();check(w.S.orders[0].id==='HIDDEN','hidden read reused when returning');
  w.invalidateViews_();p=w.loadList();take('getOrders').reject(new Error('offline'));await p;
  check(!d.querySelector('#v-list .spin')&&d.querySelector('#v-list .read-status').textContent.includes('载入失败'),'initial failure has retry instead of endless spinner');
  p=w.loadList();const previous=take('getOrders');w.logout();previous.resolve([row('PRIVATE')]);await p;
  check(!w.S.user&&Object.keys(w.VIEW_READ.cache).length===0&&!d.getElementById('olist'),'logout prevents late data reappearing');
  check(!Object.keys(w.localStorage).length&&!Object.keys(w.sessionStorage).length,'snapshots never persist to browser storage');
  w.S.user={name:'TEST',role:'admin'};w.AUTH='TEST';w.S.view='set';d.getElementById('app').innerHTML='<div id="v-set"></div>';
  w.renderSettings=()=>{};let settingLoad=w.loadSettings();check(requests.length===1&&requests[0].fn==='getAdminSettings','settings uses one authenticated request');
  take('getAdminSettings').resolve({ok:true,users:[],driver:{name:'TEST'}});await settingLoad;check(w.S.drv.name==='TEST','settings responses applied');
  await w.loadSettings();check(requests.length===0,'settings revisit reuses recent response');
  d.getElementById('v-set').oninput();Object.values(w.VIEW_READ.cache).forEach(e=>e.at-=16000);
  await w.loadSettings();check(requests.length===0,'unsaved settings are preserved when revisiting');
  const accountEdit=w.call('adminSetActive',['TEST','OTHER',false]);take('adminSetActive').resolve({ok:true});await accountEdit;
  settingLoad=w.loadSettings();take('getAdminSettings').resolve({ok:true,users:[],driver:{name:'TEST'}});await settingLoad;
  check(requests.length===0,'account changes invalidate settings cache');
  check(w.RPC_TIMINGS.every(t=>typeof t.ms==='number'&&!('args' in t)),'timing log contains no request data');
  d.getElementById('app').innerHTML='<div id="v-list"></div><div id="v-driver"></div><div id="v-dash"></div>';
  w.S.boot={driver:{phone:'',name:'TEST'},setUnits:{}};w.S.month=0;w.S.payFilter='';w.S.sel={};w.S.orderQuery='';
  w.invalidateViews_();w.warmOrders_();check(requests.length===1&&requests[0].fn==='getNavigationOrders','login warmup combines both destinations');
  w.S.view='driver';p=w.loadDriver();check(requests.length===1,'delivery click joins prefetch');
  take('getNavigationOrders').resolve({orders:[row('RECENT')],pending:[row('OLD-PENDING'),row('RECENT')],dashboard:report(8)});await p;
  check(w.S.pending[0].id==='OLD-PENDING','delivery prefetch retains old pending orders');
  w.S.view='list';await w.loadList();check(requests.length===0&&w.S.orders[0].id==='RECENT','first orders visit reuses prefetched result');
  w.S.view='dash';await w.loadDash();check(requests.length===0&&w.S.dash.total.orders===8,'first dashboard visit reuses prefetched result');
  w.S.view='driver';w.S.sel={'OLD-PENDING':true,'RECENT':true};
  Object.values(w.VIEW_READ.cache).forEach(e=>e.at-=16000);
  p=w.loadDriver();take('getOrders').resolve([row('OLD-PENDING')]);await p;
  check(w.S.sel['OLD-PENDING']&&!w.S.sel.RECENT,'refresh preserves valid selections and removes delivered selections');
  check(d.querySelector('#v-driver .read-status button').getAttribute('onclick')==='loadDriver(true)','delivery refresh targets delivery');
  const done=w.call('markDelivered',[['OLD-PENDING']]);take('markDelivered').resolve({ok:true});await done;
  p=w.loadDriver();take('getOrders').resolve([]);await p;
  check(w.S.pending.length===0&&Object.keys(w.S.sel).length===0,'delivered orders disappear after confirmed write');
  w.invalidateViews_();w.warmOrders_();const expiredWarmup=take('getNavigationOrders');w.invalidateViews_();
  expiredWarmup.resolve({orders:[row('STALE')],pending:[row('STALE')]});await flush();
  check(Object.keys(w.VIEW_READ.cache).length===0,'warmup racing mutation cannot restore stale data');
  w.warmOrders_();take('getNavigationOrders').reject(new Error('offline'));await flush();
  check(Object.keys(w.VIEW_READ.pending).length===0,'failed warmup is cleared for retry');
  w.S.user.role='driver';w.warmOrders_();check(requests.length===0,'driver login does not preload admin orders');
  const names=[...html.matchAll(/^function (\w+)\(/gm)].map(m=>m[1]);check(new Set(names).size===names.length,'no duplicate frontend functions');
  dom.window.close();console.log(`${count} performance assertions passed`);
}
main().catch(e=>{console.error(e);process.exit(1)});
