const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {JSDOM}=require('jsdom');
async function main(){
  const dom=new JSDOM(fs.readFileSync('gas/Index.html','utf8'),{runScripts:'dangerously',url:'https://test.local'});
  const w=dom.window,d=w.document,requests=[];
  w.google={script:{run:{withSuccessHandler:resolve=>({withFailureHandler:reject=>new Proxy({},{get:(_,fn)=>(...args)=>requests.push({fn,args,resolve,reject})})})}}};
  w.HAS_GS=true;w.AUTH='test';w.S.user={name:'TEST',role:'admin'};w.S.view='set';
  d.getElementById('app').innerHTML='<div id="v-set"></div>';
  const take=fn=>{const i=requests.findIndex(r=>r.fn===fn);assert.ok(i>=0,'expected '+fn);return requests.splice(i,1)[0]};
  const settings=name=>({ok:true,users:[],driver:{name,phone:'',allowance:0}});
  let p=w.loadSettings();take('getAdminSettings').resolve(settings('FIRST'));await p;
  const el=d.getElementById('v-set'),original=d.getElementById('dvName');
  w.VIEW_READ.cache.adminSettings.at-=16000;
  p=w.loadSettings();assert.equal(d.getElementById('dvName'),original,'stale form stays visible');
  original.value='MY EDIT';original.dispatchEvent(new w.Event('input',{bubbles:true}));
  take('getAdminSettings').resolve(settings('REMOTE EDIT'));await p;
  assert.equal(d.getElementById('dvName').value,'MY EDIT','in-flight refresh cannot erase typing');
  let save=w.call('markPaid',[{}]);take('markPaid').resolve({ok:true});await save;
  await w.loadSettings();assert.equal(d.getElementById('dvName').value,'MY EDIT','unrelated order save preserves form');
  assert.equal(requests.length,0,'unrelated save does not reload settings');
  el._settingsDirty=false;w.VIEW_READ.cache.adminSettings.at-=16000;
  p=w.loadSettings();take('getAdminSettings').reject(Error('offline'));await p;
  assert.equal(d.getElementById('dvName').value,'MY EDIT','offline retains visible form');
  assert.match(el.textContent,/更新失败/);
  p=w.loadSettings();take('getAdminSettings').resolve(settings('RECOVERED'));await p;
  assert.equal(d.getElementById('dvName').value,'RECOVERED','retry updates clean form');
  const orderKey='getOrders'+JSON.stringify([{month:'',pay:'',limit:300}]);
  w.VIEW_READ.cache[orderKey]={data:[{id:'A'}],at:Date.now()};
  const orderEpoch=w.readEpoch_(orderKey);
  save=w.call('makeInvoicePdf',[{}]);take('makeInvoicePdf').resolve({ok:true});await save;
  assert.ok(w.VIEW_READ.cache[orderKey],'PDF creation retains order cache');
  assert.equal(w.readEpoch_(orderKey),orderEpoch);
  save=w.call('adminSetActive',[]);take('adminSetActive').resolve({ok:true});await save;
  assert.ok(w.VIEW_READ.cache[orderKey],'account change retains orders');
  assert.ok(!w.VIEW_READ.cache.adminSettings,'account change invalidates settings');
  p=w.loadSettings();const stale=take('getAdminSettings');
  save=w.call('adminSetDriver',[]);take('adminSetDriver').resolve({ok:true});await save;
  assert.ok(!w.VIEW_READ.cache[orderKey],'driver allowance change invalidates dashboard/order group');
  stale.resolve(settings('STALE'));await new Promise(resolve=>setImmediate(resolve));
  take('getAdminSettings').resolve(settings('LATEST'));await p;
  assert.equal(d.getElementById('dvName').value,'LATEST','settings save race refetches');
  p=w.loadSettings(true);const late=take('getAdminSettings');
  w.confirm=()=>true;w.logout();late.reject(Error('offline'));await p;
  assert.ok(!d.getElementById('dvName'),'late failure cannot recreate logged-out form');
  dom.window.close();

  const c={Session:{getScriptTimeZone:()=> 'Asia/Kuala_Lumpur'},Utilities:{formatDate:()=> '10/09/2026'}};
  vm.createContext(c);vm.runInContext(fs.readFileSync('gas/Code.js','utf8'),c);
  let reads=0;c.config_=()=>({COMPANY:'TEST'});c.invBrandList_=()=>[];c.invBrandOf_=()=>'';
  c.ensureCols_=()=>{reads++;return {rows:[{SET_TYPE:'BAG','单位':'PCS'},{SET_TYPE:'KIT','单位':'SET'}]}};
  const orders=Array.from({length:20},(_,i)=>({SALESMAN:'TEST',BRANCH:'BRANCH',SET_TYPE:i%2?'KIT':'BAG',QTY:2,UNIT_PRICE:10,TOTAL_INCOME:20,DRIVER_FEE:1}));
  const text=c.buildWaText_(orders);
  assert.equal(reads,1,'20 delivery lines read the price table once');
  assert.equal((text.match(/2 pcs/g)||[]).length,10,'pcs retained');
  assert.equal((text.match(/2 set/g)||[]).length,10,'set retained');
  assert.match(text,/共 20 单 · 40 件 · RM 400/);
  console.log('Scoped refresh, settings editing/races/offline, and 20-order delivery checks passed');
}
main().catch(e=>{console.error(e);process.exit(1)});
